In [1]:
import pandas as pd
import numpy as np

In [2]:
train_inter = pd.read_csv('../dataset/raw/browsing_train.csv')
test_merged = pd.read_csv('../dataset/raw/browsing_test.csv')

In [3]:
train_search = pd.read_csv('../dataset/raw/sku_to_content.csv')

# 分离session 和 search

In [4]:
inter_cols = train_inter.columns
search_cols = test_merged.columns

In [5]:
search_mask = test_merged['is_search'] == True
test_search = test_merged[search_mask][search_cols]
test_search.head()

,session_id_hash,query_vector,clicked_skus_hash,product_skus_hash,server_timestamp_epoch_ms,event_type,product_action,product_sku_hash,hashed_url,is_search
3,000106ea084ce19705d7d6889dfd3cb4bd2d596c8b31bd...,"[0.0711296796798706, 0.3248276710510254, 0.023...",NaN,['cdcfae35b9136964fffa164db83293bc22ccc5cb8572...,1557259563467,NaN,NaN,NaN,NaN,True
4,000106ea084ce19705d7d6889dfd3cb4bd2d596c8b31bd...,"[-0.1051841750741005, 0.05710870400071144, -0....",NaN,['2d56a573739252332916de9219adfa0cf4e33c306c03...,1557259580980,NaN,NaN,NaN,NaN,True
5,000106ea084ce19705d7d6889dfd3cb4bd2d596c8b31bd...,"[-0.022189028561115265, 0.24036407470703125, -...",NaN,['920f41d3f647094292ee9813cd169e73910427c2b292...,1557260488542,NaN,NaN,NaN,NaN,True
6,000106ea084ce19705d7d6889dfd3cb4bd2d596c8b31bd...,"[0.015821531414985657, 0.15578031539916992, -0...",NaN,['6770b1b5f49d1176215d44ddda0e3e83bd2e2c010e4d...,1557260554468,NaN,NaN,NaN,NaN,True
39,00048b27755f15130e6ae54afb2ef1195af909cd06d349...,"[-0.1898450404405594, -0.360311359167099, 0.16...",['fcd39923dfec7c0373c0263ce141788ed99e7c55b1de...,['4eb881935e535eeba9a5248173d60ba71be2915e3fcd...,1555868397735,NaN,NaN,NaN,NaN,True

In [6]:
inter_mask = test_merged['is_search'] == False
test_inter = test_merged[inter_mask][inter_cols]
test_inter.head()

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url
0,000028429ab6afd40f2a4d59c183ea46390fdfa3d04c80...,event_product,detail,4641de8468a39c53a151e8ee5f3bd731e69b3d7ac61335...,1557432435044,4f7f239c607d10b0843ceeccb98aecb382f8c18a931758...
1,000074f533a4fb893af451e4d436d326ddd2a7e83151a9...,event_product,detail,7571fbadb886e669ea4ac666b585fcc798c1f5970867c5...,1555443439867,0301401ac53e67e319036bbb0c12a4715ec5df45614023...
2,0000a6d196680bebf931ad7670f479c5c5357b3f1f8943...,pageview,NaN,NaN,1556729588695,9cfe9b259c3c4029a5d20e3542905d07ccf50d9a3bd4d7...
7,0001f7b93896b89ad8272f56cc2fe3ae39e9624d31ab4f...,event_product,detail,9aa8dec189cb97b3fea1a11c2452b62fc67ce64431db0b...,1557448538017,c3e6a76842aa75c2315197a9771a95655057abcd7a08d6...
8,0001f7b93896b89ad8272f56cc2fe3ae39e9624d31ab4f...,event_product,detail,9aa8dec189cb97b3fea1a11c2452b62fc67ce64431db0b...,1557448562230,c3e6a76842aa75c2315197a9771a95655057abcd7a08d6...

In [7]:
assert test_search.shape[0] + test_inter.shape[0] == test_merged.shape[0]

In [9]:
test_inter.to_csv('../dataset/raw/browsing_test.csv', index=False)
test_search.to_csv('../dataset/raw/search_test.csv', index=False)